repos:
  - repo: https://github.com/python/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v3.4.0
#    hooks:
#      - id: check-docstring-first
#        stages:
#          - commit
#          - push
#      - id: check-merge-conflict
#        stages:
#          - push
#      - id: double-quote-string-fixer
#        stages:
#          - commit
#          - push
#      - id: trailing-whitespace
#        stages:
#          - commit
#          - push
#      - id: end-of-file-fixer
#        stages:
#          - commit
#          - push
